# Generated by Django 6.0.4 on 2026-04-29 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("CXR", "Chest X-Ray")],
                        help_text="Modality/exam type this flow applies to. One active flow definition per type.",
                        max_length=32,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Increment when the structure changes. Frontend can cache by flow_type + version.",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable display name, e.g. 'Chest X-Ray Systematic Review'.",
                        max_length=128,
                    ),
                ),
                (
                    "structure",
                    models.JSONField(
                        help_text="Full checklist structure as JSON. Top-level keys are section IDs (A, B, C, D, E, 2H, HG). Each section contains: section_id, section_label, groups[] → group_name, items[] → item_id, item_text, options[]."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active flows are served to the frontend. Deactivate rather than delete when retiring a version.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flow",
                "verbose_name_plural": "Flows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "study_uid",
                    models.CharField(
                        db_index=True,
                        help_text="DICOM Study Instance UID — links this report to the study in Orthanc.",
                        max_length=255,
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        help_text="Completed checklist payload. Structure mirrors the flow's sections. Each item contains: item_id, status (normal|finding|not_reviewed), selected_options[], free_text. Each section may contain a section_note."
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of final submission. Null while status=draft.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flow",
                    models.ForeignKey(
                        help_text="The flow definition this report was completed against.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="core.flow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow Report",
                "verbose_name_plural": "Flow Reports",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("study_uid", "flow"),
                        name="unique_submitted_report_per_study_flow",
                    )
                ],
            },
        ),
    ]
