# Generated by Django 6.0.4 on 2026-05-06 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studyreport",
            name="submitted_by",
            field=models.ForeignKey(
                help_text="The user who submitted this report.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flow_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
