# Generated by Django 6.0.4 on 2026-05-07 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studyreport_submitted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studyreport',
            name='unique_submitted_report_per_study_flow',
        ),
        migrations.AddField(
            model_name='studyreport',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this report (tracks drafts too).', on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this report (null while drafting).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studyreport',
            constraint=models.UniqueConstraint(fields=('study_uid', 'flow', 'created_by'), name='unique_submitted_report_per_study_flow'),
        ),
    ]
