# Generated by Django 6.0.4 on 2026-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_studyreport_unique_submitted_report_per_study_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyreport',
            name='report_data',
            field=models.JSONField(default={}, help_text="Completed checklist payload. Structure mirrors the flow's sections. Each item contains: item_id, status (normal|finding|not_reviewed), selected_options[], free_text. Each section may contain a section_note.", null=True),
        ),
    ]
