# Generated by Django 6.0.4 on 2026-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_studyreport_report_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyreport",
            name="report_data",
            field=models.JSONField(
                default=dict,
                help_text="Completed checklist payload. Structure mirrors the flow's sections. Each item contains: item_id, status (normal|finding|not_reviewed), selected_options[], free_text. Each section may contain a section_note.",
                null=True,
            ),
        ),
    ]
