# Generated by Django 6.0.4 on 2026-06-03 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_studyreport_report_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this report (tracks drafts too).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
