# Generated by Django 6.0.4 on 2026-06-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_studyreport_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16),
        ),
    ]
