# Generated by Django 6.0.4 on 2026-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studyreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyreport',
            name='report_document_md',
            field=models.CharField(blank=True, help_text='Complete report returned from LLM', null=True),
        ),
    ]
