# Generated by Django 6.0.4 on 2026-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_studyreport_report_document_md"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyreport",
            name="report_document_md",
            field=models.TextField(
                blank=True, help_text="Complete report returned from LLM", null=True
            ),
        ),
    ]
